### ISSUE TITLE
There may missing an RBAC file

### ISSUE THREAD

**Issue by Derrings** [mKaloer/TFServingCache#18]
We attempted to deploy this project through helm, but in the end we found that the cache container requires access to pods and endpoints, which we did not provide. So we added a Role to the cluster and bound it to a ServiceAccount, ultimately solving this problem. If an rbac file is added to helm templates, it will be good.

**Comment by mKaloer** [comment]
Hi @Derrings,

Thanks for reporting this. You are right, and I wonder why it works on our cluster. Anyways, I've created a PR (#19). If you have time, can you have a quick look and see if it matches with your working roles? Thanks.
