### ISSUE TITLE
Create Helm chart

### ISSUE THREAD

**Issue by mKaloer** [mKaloer/TFServingCache#2]
In order to ease the deployment, it would be nice to have a Helm chart for kubernetes. As part of this, there should be an easy guide on how to get it up and running on Minikube.

**Comment by AlexMihalev** [comment]
I am very interested in the helm chart also, maybe I can start working on this item?
If so, my plan will be:
- create helm chart for TFServingCache deployment that will include:
  - TFServing and TFServingCache in a single pod
  - customizable ingress rules, I think the TFServingCache can be used   
  - config map to share TFServingCache's configuration across the cluster
as a load balancer itself and it will usable in scenarios when SSL offload is not an issue
- create a sample "umbrella" helm chart (ideally, this chart will include all necessary dependencies and can be used for integration testing), that will include 
  - dependencies on the chart described above
  - ingress controller (http, grpc?)
  - configurable discovery service (consul, etcd, .. )
  - Prometheus (or something that can visualize performance metrics)
  - some implementation of S3 like Minio (to test integration with S3, authentication, and authorization)

**Comment by mKaloer** [comment]
Absolutely. I think we agree on the requirements for the helm charts. For the TFServingCache deployment, I suggest that we only support the kubernetes-based discovery service (at least for now), since this is the simplest to get up and running and require no external dependencies. The helm chart should have sane defaults that will make this easy, i.e. the right selectors. I can assist in defining the details.

Regarding Prometheus, I think there are two approaches:
1) To include a dependency to [Prometheus-Operator](https://github.com/helm/charts/tree/master/stable/prometheus-operator) and create an operator
2) To create a Prometheus operator resource if the Prometheus Operator chart is installed

You can take a look at the `helm-chart` branch. It's a bit outdated but may work as a starting point.
